### ISSUE TITLE
meta-python missing

### ISSUE THREAD

**Issue by dkutsanov** [xbolshe/galileo-sources#1]
when i give bitbake comand it gives me an error (the folder /meta-openembedded/meta-python is missing):

ERROR: Layer 'networking-layer' depends on layer 'meta-python', but this layer is not enabled in your configuration

**Comment by xbolshe** [comment]
Hi,

I haven't such error during a clean build. 
May you provide more information about?
Have you added *.bb, *.bbappend, *.conf files and new layers?
May you provide a full bitbake's error log?

BR,
xbolshe

**Comment by dkutsanov** [comment]
I'm trying to build the image using your manual. So the only steps I made are those provided by you.
May you explain me which *.bb, *.bbappend, *.conf files and new layers I should add and how, in order do build properly this basic image?

**Comment by xbolshe** [comment]
I see. Nothing need to be added to compile it properly. A compilation process is the same as described in Intel's manual. Anyway need to identify a reason of the problem. Now I have no detailed information about. What OS version do you use?

BR,
xbolshe

**Comment by dkutsanov** [comment]
I'm using kubuntu 14.04.4 fresh install, with all needed dependencies from your manual and intel manual in order to build a custom image.

**Comment by xbolshe** [comment]
Have you installed packets using packets.sh ? May you provide a full bitbake's error log?

**Comment by dkutsanov** [comment]
Yes, I did.
I used bitbake –v iamge-full 2>&1 | tee error_build.log
and the only thing in the log is:

ERROR: Layer 'networking-layer' depends on layer 'meta-python', but this layer is not enabled in your configuration

Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by xbolshe** [comment]
What is a content of {your_installation}/iot_1.2.0_kernel_3.19.8/meta-openembedded/meta-networking/conf/layer.conf ?

**Comment by dkutsanov** [comment]
sry for bad formatting. there is pastebin link
http://pastebin.com/5h4in5fR

**Comment by xbolshe** [comment]
I see. Need to disable two lines like shown below:

#LAYERDEPENDS_networking-layer = "openembedded-layer"
#LAYERDEPENDS_networking-layer = "meta-python"

May you provide a content of {your_installation}/repo-ext/meta-openembedded/.git/logs/{all_files} ?

**Comment by dkutsanov** [comment]
the folder logs:

HEAD http://pastebin.com/Yvfw1v0W
/refs/heads/dizzy http://pastebin.com/PvpVDn9E
/refs/remotes/origin/HEAD http://pastebin.com/cbSLp2Ym

Now I'll try to edit layer.conf as you suggested before and try to bitbake again

**Comment by dkutsanov** [comment]
the bitbake command is working now, so I need to wait until it finishes.

**Comment by xbolshe** [comment]
What is an output of "git --version" ?

**Comment by dkutsanov** [comment]
git version 1.9.1

**Comment by xbolshe** [comment]
I use git 2.1.0. 
It seems one patch does not work in your case.

**Comment by dkutsanov** [comment]
ok, thank you. so should I revert the changes made in /iot_1.2.0_kernel_3.19.8/meta-openembedded/meta-networking/conf/layer.conf and try to bitbake again?

**Comment by xbolshe** [comment]
No need to do because you have patched it manually.

**Comment by dkutsanov** [comment]
Just for info, I updated git to 2.7.4 and that conflict persist so I have to manualy patch it again.

**Comment by dkutsanov** [comment]
I compiled disabling 2 lines lke you suggested and the build proccess finished with some warning but no errors. Anyway I tried it on Galileo but it stucks after the grub menu at this screen (http://i.imgur.com/kGT7KBw.png)

I don't want bother you but there should be something missing in this build because I can properly build from bsp (provided by intel) but not this one and I didn't modify anything except the 2 lines you that you suggested.

P.S. may I ask you what is your linux configuration in order to build this? (linux distro, gcc version etc)

**Comment by xbolshe** [comment]
I have uploaded an updated instruction. I have checked it with a clean installation of Kubuntu 14.04.4 and default toools: GCC 4.8.4, GIT 1.9.1

Please try it and provide an output of ./setup.sh

Thanks.

BR,
xbolshe

**Comment by dkutsanov** [comment]
With git 1.9.1 the image builds perfectly and works great.
Wifi driver must be added manualy anyway in order to work with N 7260 card.

P.S. if you are using (k)ubuntu 14.04.4 and install all the dependencies with the file packets.sh git will try to upgrade to 2.8.4 version. And that version does not work properly. So maybe you should specify in the manual that git must be 1.9.1.

BR,
bruc0
